apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://10.96.71.94:8200"
      path: "nerdquecorre"
      version: "v1"
      auth:
        tokenSecretRef:
            name: "vault-policy-token"
            key: "token"
