apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: nerdquecorre-senhas
    creationPolicy: Owner
  data:
  - secretKey: palavra1
    remoteRef:
      key: nerdquecorre/senha
      property: palavra1
  - secretKey: palavra2
    remoteRef:
      key: nerdquecorre/senha
      property: palavra2
