apiVersion: v1
kind: Pod
metadata:
  name: giropops-pod
spec:
  containers:
  - name: giropops-container
    image: nginx
    env: #Inicio da definição da variável
    - name: USERNAME #Nome da variável a ser usada no pod
      valueFrom: 
        secretKeyRef:
          name: giropops-secret
          key: username
    - name: PASSWORD #Nome da variável a ser usada no pod
      valueFrom: 
        secretKeyRef:
          name: giropops-secret
          key: password
