apiVersion: v2
name: giropops-senhas
description: Esse é o chart do giropops senhas, utilizado nos laboratórios de kubernetes
version: 0.1.0
appVersion: 0.1.0
sources: 
  - https://github.com/badtuxx/giropops-senhas 
  