apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girus
    service: webserver
  name: girus
spec:
  containers:
  - image: nginx
    name: ngnix
    resources: {}
  - image: busybox
    name: busybox
    args:
    -  sleep
    -  "600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
